// All scam types supported by the app — mirrors the web report pages
export const SCAM_TYPES = [
  { key: 'romance', label: 'Romance Scam', icon: '💔', slug: 'report-romance-scam' },
  { key: 'crypto', label: 'Cryptocurrency Scam', icon: '₿', slug: 'report-crypto-scam' },
  { key: 'pig_butchering', label: 'Pig Butchering', icon: '🐷', slug: 'report-pig-butchering-scam' },
  { key: 'phishing', label: 'Phishing', icon: '🎣', slug: 'report-phishing-scam' },
  { key: 'investment', label: 'Investment Scam', icon: '📈', slug: 'report-investment-scam' },
  { key: 'identity_theft', label: 'Identity Theft', icon: '🪪', slug: 'report-identity-theft' },
  { key: 'tech_support', label: 'Tech Support Scam', icon: '💻', slug: 'report-tech-support-scam' },
  { key: 'online_shopping', label: 'Online Shopping Scam', icon: '🛒', slug: 'report-online-shopping-scam' },
  { key: 'facebook_marketplace', label: 'Facebook Marketplace', icon: '🏪', slug: 'report-facebook-marketplace-scam' },
  { key: 'employment', label: 'Employment Scam', icon: '💼', slug: 'report-employment-scam' },
  { key: 'gift_card', label: 'Gift Card Scam', icon: '🎁', slug: 'report-gift-card-scam' },
  { key: 'government_impersonation', label: 'Government Impersonation', icon: '🏛️', slug: 'report-government-impersonation-scam' },
  { key: 'sextortion', label: 'Sextortion', icon: '⚠️', slug: 'report-sextortion-scam' },
  { key: 'rental', label: 'Rental Scam', icon: '🏠', slug: 'report-rental-scam' },
  { key: 'business_email', label: 'Business Email Compromise', icon: '📧', slug: 'report-business-email-scam' },
  { key: 'lottery', label: 'Lottery / Sweepstakes', icon: '🎰', slug: 'report-lottery-scam' },
  { key: 'credit_card', label: 'Credit Card Fraud', icon: '💳', slug: 'report-credit-card-fraud' },
  { key: 'charity', label: 'Charity Scam', icon: '🎗️', slug: 'report-charity-scam' },
  { key: 'impersonation', label: 'Impersonation Scam', icon: '🎭', slug: 'report-impersonation-scam' },
  { key: 'elder_fraud', label: 'Elder Fraud', icon: '👴', slug: 'report-elder-fraud' },
  { key: 'deepfake', label: 'Deepfake Scam', icon: '🤖', slug: 'report-deepfake-scam' },
  { key: 'pet', label: 'Pet Scam', icon: '🐶', slug: 'report-pet-scam' },
  { key: 'grandparent', label: 'Grandparent Scam', icon: '📞', slug: 'report-grandparent-scam' },
  { key: 'payment_app', label: 'Payment App Scam', icon: '📱', slug: 'report-payment-app-scam' },
  { key: 'advance_fee', label: 'Advance Fee Scam', icon: '💰', slug: 'report-advance-fee-scam' },
  { key: 'social_media', label: 'Social Media Scam', icon: '📲', slug: 'report-social-media-scam' },
  { key: 'military', label: 'Military Scam', icon: '🎖️', slug: 'report-military-scam' },
  { key: 'sugar_daddy', label: 'Sugar Daddy/Mommy Scam', icon: '🍬', slug: 'report-sugar-daddy-scam' },
  { key: 'car', label: 'Car Scam', icon: '🚗', slug: 'report-car-scam' },
  { key: 'real_estate', label: 'Real Estate Scam', icon: '🏡', slug: 'report-real-estate-scam' },
  { key: 'ransomware', label: 'Ransomware', icon: '🔒', slug: 'report-ransomware' },
  { key: 'crypto_wallet', label: 'Crypto Wallet Scam', icon: '👛', slug: 'report-crypto-wallet' },
  { key: 'fake_social_media', label: 'Fake Social Media', icon: '👤', slug: 'report-fake-social-media' },
  { key: 'fraudulent_website', label: 'Fraudulent Website', icon: '🌐', slug: 'report-fraudulent-website' },
];

export const QUICK_REPORT_TYPES = [
  { key: 'website_report', label: 'Scam Website', icon: '🌐', placeholder: 'e.g. fake-shop.com' },
  { key: 'crypto_wallet_report', label: 'Crypto Wallet', icon: '👛', placeholder: 'e.g. 0x1234…abcd' },
  { key: 'social_media_report', label: 'Social Media Profile', icon: '👤', placeholder: 'e.g. @scammer123' },
  { key: 'phone_report', label: 'Phone Number', icon: '📞', placeholder: 'e.g. +1 (555) 123-4567' },
  { key: 'email_report', label: 'Email Address', icon: '📧', placeholder: 'e.g. scammer@email.com' },
];
